<a href="https://colab.research.google.com/github/supriyapawar9500-cell/python/blob/main/PANDASCLEANING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import pandas as pd
from io import StringIO

# Student dataset in CSV format
csv_data = """student_id,name,gender,study_hours,marks
101,Amit,Male,2,65
102,Priya,Female,4,82
103,Rahul,Male,3,75
104,Sneha,Female,5,90
105,Rohan,Male,,68
106,Neha,Female,6,95
107,Karan,Male,2,
108,Pooja,Female,4,85
109,Arjun,Male,3,72
102,Priya,Female,4,82
"""

# Load dataset into Pandas
df = pd.read_csv(StringIO(csv_data))

print("Original Data:")
print(df)
print(df.info())

Original Data:
   student_id   name  gender  study_hours  marks
0         101   Amit    Male          2.0   65.0
1         102  Priya  Female          4.0   82.0
2         103  Rahul    Male          3.0   75.0
3         104  Sneha  Female          5.0   90.0
4         105  Rohan    Male          NaN   68.0
5         106   Neha  Female          6.0   95.0
6         107  Karan    Male          2.0    NaN
7         108  Pooja  Female          4.0   85.0
8         109  Arjun    Male          3.0   72.0
9         102  Priya  Female          4.0   82.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student_id   10 non-null     int64
 1   name         10 non-null     object
 2   gender       10 non-null     object
 3   study_hours  9 non-null      float64
 4   marks        9 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 532.0+ bytes
None

In [ ]:
df["gender"]=["Male","Female","Male","Female","Male","Female","Male","Female","Male","Female"]
df

   student_id   name  gender  study_hours  marks
0         101   Amit    Male          2.0   65.0
1         102  Priya  Female          4.0   82.0
2         103  Rahul    Male          3.0   75.0
3         104  Sneha  Female          5.0   90.0
4         105  Rohan    Male          NaN   68.0
5         106   Neha  Female          6.0   95.0
6         107  Karan    Male          2.0    NaN
7         108  Pooja  Female          4.0   85.0
8         109  Arjun    Male          3.0   72.0
9         102  Priya  Female          4.0   82.0

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student_id   10 non-null     int64
 1   name         10 non-null     object
 2   gender       10 non-null     object
 3   study_hours  9 non-null      float64
 4   marks        9 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 532.0+ bytes
None

In [ ]:
df["study_hours"]=pd.to_numeric(df["study_hours"],errors="coerce")

In [ ]:
#Remove duplicates based on all columns(or key columns like student_id, name)
df=df.drop_duplicates(subset=["student_id","name"], keep="first")
df

   student_id   name  gender  study_hours  marks
0         101   Amit    Male          2.0   65.0
1         102  Priya  Female          4.0   82.0
2         103  Rahul    Male          3.0   75.0
3         104  Sneha  Female          5.0   90.0
4         105  Rohan    Male          NaN   68.0
5         106   Neha  Female          6.0   95.0
6         107  Karan    Male          2.0    NaN
7         108  Pooja  Female          4.0   85.0
8         109  Arjun    Male          3.0   72.0

In [ ]:
#handle missing values
#for numeric columns filled with median.
df["study_hours"]=df["study_hours"].fillna(df["study_hours"].median())
df

   student_id   name  gender  study_hours  marks
0         101   Amit    Male          2.0   65.0
1         102  Priya  Female          4.0   82.0
2         103  Rahul    Male          3.0   75.0
3         104  Sneha  Female          5.0   90.0
4         105  Rohan    Male          3.5   68.0
5         106   Neha  Female          6.0   95.0
6         107  Karan    Male          2.0    NaN
7         108  Pooja  Female          4.0   85.0
8         109  Arjun    Male          3.0   72.0

In [ ]:
df["marks"]=df["marks"].fillna(df["marks"].median())
df

   student_id   name  gender  study_hours  marks
0         101   Amit    Male          2.0   65.0
1         102  Priya  Female          4.0   82.0
2         103  Rahul    Male          3.0   75.0
3         104  Sneha  Female          5.0   90.0
4         105  Rohan    Male          3.5   68.0
5         106   Neha  Female          6.0   95.0
6         107  Karan    Male          2.0   78.5
7         108  Pooja  Female          4.0   85.0
8         109  Arjun    Male          3.0   72.0

In [ ]:
#Basic statistics
print("Basic Statistics: ")
print(df[["study_hours","marks"]].describe())

Basic Statistics:
       study_hours      marks
count     9.000000   9.000000
mean      3.611111  78.944444
std       1.317616  10.026354
min       2.000000  65.000000
25%       3.000000  72.000000
50%       3.500000  78.500000
75%       4.000000  85.000000
max       6.000000  95.000000

In [ ]:
#Mean, Median
print("Mean: ")
print(df[["study_hours","marks"]].mean())
print(df[["study_hours","marks"]].median())

Mean:
study_hours     3.611111
marks          78.944444
dtype: float64
study_hours     3.5
marks          78.5
dtype: float64

In [ ]:
#Value counts for categorial column
print(df["gender"].value_counts())
df

gender
Male      5
Female    4
Name: count, dtype: int64

   student_id   name  gender  study_hours  marks
0         101   Amit    Male          2.0   65.0
1         102  Priya  Female          4.0   82.0
2         103  Rahul    Male          3.0   75.0
3         104  Sneha  Female          5.0   90.0
4         105  Rohan    Male          3.5   68.0
5         106   Neha  Female          6.0   95.0
6         107  Karan    Male          2.0   78.5
7         108  Pooja  Female          4.0   85.0
8         109  Arjun    Male          3.0   72.0