<a href="https://colab.research.google.com/github/supriyapawar9500-cell/python/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [235]:
import pandas as pd

In [236]:
s=pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [237]:
s.dtype

dtype('int64')

In [238]:
s.values

array([10, 20, 30, 40, 50])

In [239]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [240]:
s.name

In [241]:
s.name="numbers"
s

0    10
1    20
2    30
3    40
4    50
Name: numbers, dtype: int64

In [242]:
#indexing
s[0]

np.int64(10)

In [243]:
s[0:2]

0    10
1    20
Name: numbers, dtype: int64

In [244]:
s[2:4]

2    30
3    40
Name: numbers, dtype: int64

In [245]:
#iloc -> location based indexing
s.iloc[3]

np.int64(40)

In [246]:
s.iloc[[1,3,4]]

1    20
3    40
4    50
Name: numbers, dtype: int64

In [247]:
s.name="calories"
s

0    10
1    20
2    30
3    40
4    50
Name: calories, dtype: int64

In [248]:
index=["apple","banana","grapes","orange","strawberry"]

In [249]:
s.index=index
s

apple         10
banana        20
grapes        30
orange        40
strawberry    50
Name: calories, dtype: int64

In [250]:
s['grapes']

np.int64(30)

In [251]:
s.iloc[2]

np.int64(30)

In [252]:
#loc ->labeled based indexing
s['banana':'orange']

banana    20
grapes    30
orange    40
Name: calories, dtype: int64

In [253]:
s.loc[['grapes','banana','orange']]

grapes    30
banana    20
orange    40
Name: calories, dtype: int64

In [254]:
fruit_protein ={
    "Avacado":2.0,
    "Guava":2.6,
    "blackberries":2.0,
    "Oranges":0.9,
    "Banana":1.1,
    "Apple":0.3,
    "Kiwi":1.1,
    "Pomegranate":1.7,
    "Mango":0.8,
    "Cherries":1.0
    }

In [255]:
fruit_protein

{'Avacado': 2.0,
 'Guava': 2.6,
 'blackberries': 2.0,
 'Oranges': 0.9,
 'Banana': 1.1,
 'Apple': 0.3,
 'Kiwi': 1.1,
 'Pomegranate': 1.7,
 'Mango': 0.8,
 'Cherries': 1.0}

In [256]:
s2=pd.Series(fruit_protein)
s2

Avacado         2.0
Guava           2.6
blackberries    2.0
Oranges         0.9
Banana          1.1
Apple           0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
dtype: float64

In [257]:
s2.name="protein"
s2

Avacado         2.0
Guava           2.6
blackberries    2.0
Oranges         0.9
Banana          1.1
Apple           0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: protein, dtype: float64

In [258]:
#Conditional selection
s2[s2>1]

Avacado         2.0
Guava           2.6
blackberries    2.0
Banana          1.1
Kiwi            1.1
Pomegranate     1.7
Name: protein, dtype: float64

In [259]:
import numpy as np
data ={
    "Name":["Alice","Bob","supriya","Sai","Shravani","Alice"],
    "Age":[25,30,35,np.nan,29,25],
    "Department":["HR","IT","Finance","IT","HR","Hr"],
    "Salary":[50000,60000,70000,62000,np.nan,50000]
}
data

{'Name': ['Alice', 'Bob', 'supriya', 'Sai', 'Shravani', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'Hr'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [260]:
df=pd.DataFrame(data)
df

       Name   Age Department   Salary
0     Alice  25.0         HR  50000.0
1       Bob  30.0         IT  60000.0
2   supriya  35.0    Finance  70000.0
3       Sai   NaN         IT  62000.0
4  Shravani  29.0         HR      NaN
5     Alice  25.0         Hr  50000.0

In [261]:
df.head()

       Name   Age Department   Salary
0     Alice  25.0         HR  50000.0
1       Bob  30.0         IT  60000.0
2   supriya  35.0    Finance  70000.0
3       Sai   NaN         IT  62000.0
4  Shravani  29.0         HR      NaN

In [262]:
df.tail()

       Name   Age Department   Salary
1       Bob  30.0         IT  60000.0
2   supriya  35.0    Finance  70000.0
3       Sai   NaN         IT  62000.0
4  Shravani  29.0         HR      NaN
5     Alice  25.0         Hr  50000.0

In [263]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Department  6 non-null      object
 3   Salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [264]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   28.800000  58400.000000
std     4.147288   8532.291603
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  60000.000000
75%    30.000000  62000.000000
max    35.000000  70000.000000

In [265]:
df.iloc[1:3, :2]

      Name   Age
1      Bob  30.0
2  supriya  35.0

In [266]:
df.loc[1:3, ["Age","Department"]]

    Age Department
1  30.0         IT
2  35.0    Finance
3   NaN         IT

In [267]:
df[["Age","Department"]]

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0    Finance
3   NaN         IT
4  29.0         HR
5  25.0         Hr

In [268]:
df.rename(columns= {"Department":"Dept"}, inplace=True)
df

       Name   Age     Dept   Salary
0     Alice  25.0       HR  50000.0
1       Bob  30.0       IT  60000.0
2   supriya  35.0  Finance  70000.0
3       Sai   NaN       IT  62000.0
4  Shravani  29.0       HR      NaN
5     Alice  25.0       Hr  50000.0

In [269]:
df.drop("Age", axis=1)

       Name     Dept   Salary
0     Alice       HR  50000.0
1       Bob       IT  60000.0
2   supriya  Finance  70000.0
3       Sai       IT  62000.0
4  Shravani       HR      NaN
5     Alice       Hr  50000.0

In [270]:
df.shape

(6, 4)

In [271]:
df.values

array([['Alice', 25.0, 'HR', 50000.0],
       ['Bob', 30.0, 'IT', 60000.0],
       ['supriya', 35.0, 'Finance', 70000.0],
       ['Sai', nan, 'IT', 62000.0],
       ['Shravani', 29.0, 'HR', nan],
       ['Alice', 25.0, 'Hr', 50000.0]], dtype=object)

In [272]:
df["Salary"] =df["Salary"]+5000
df

       Name   Age     Dept   Salary
0     Alice  25.0       HR  55000.0
1       Bob  30.0       IT  65000.0
2   supriya  35.0  Finance  75000.0
3       Sai   NaN       IT  67000.0
4  Shravani  29.0       HR      NaN
5     Alice  25.0       Hr  55000.0

In [273]:
df["Salary"].unique()

array([55000., 65000., 75000., 67000.,    nan])

In [274]:
df["Dept"].value_counts()

Dept
HR         2
IT         2
Finance    1
Hr         1
Name: count, dtype: int64

In [275]:
df["Promoted Salary"]=df["Salary"]*10

In [276]:
df

       Name   Age     Dept   Salary  Promoted Salary
0     Alice  25.0       HR  55000.0         550000.0
1       Bob  30.0       IT  65000.0         650000.0
2   supriya  35.0  Finance  75000.0         750000.0
3       Sai   NaN       IT  67000.0         670000.0
4  Shravani  29.0       HR      NaN              NaN
5     Alice  25.0       Hr  55000.0         550000.0

In [277]:
#Data cleaning
df.isnull().sum()

Name               0
Age                1
Dept               0
Salary             1
Promoted Salary    1
dtype: int64

In [278]:
df.dropna(how="any")

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  supriya  35.0  Finance  75000.0         750000.0
5    Alice  25.0       Hr  55000.0         550000.0

In [279]:
df

       Name   Age     Dept   Salary  Promoted Salary
0     Alice  25.0       HR  55000.0         550000.0
1       Bob  30.0       IT  65000.0         650000.0
2   supriya  35.0  Finance  75000.0         750000.0
3       Sai   NaN       IT  67000.0         670000.0
4  Shravani  29.0       HR      NaN              NaN
5     Alice  25.0       Hr  55000.0         550000.0

In [280]:
df.dropna(how="all")

       Name   Age     Dept   Salary  Promoted Salary
0     Alice  25.0       HR  55000.0         550000.0
1       Bob  30.0       IT  65000.0         650000.0
2   supriya  35.0  Finance  75000.0         750000.0
3       Sai   NaN       IT  67000.0         670000.0
4  Shravani  29.0       HR      NaN              NaN
5     Alice  25.0       Hr  55000.0         550000.0

In [281]:
df.fillna(0)

       Name   Age     Dept   Salary  Promoted Salary
0     Alice  25.0       HR  55000.0         550000.0
1       Bob  30.0       IT  65000.0         650000.0
2   supriya  35.0  Finance  75000.0         750000.0
3       Sai   0.0       IT  67000.0         670000.0
4  Shravani  29.0       HR      0.0              0.0
5     Alice  25.0       Hr  55000.0         550000.0

In [282]:
df["Age"].fillna(df["Age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [283]:
df["Salary"].fillna(df["Salary"].median())

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4    65000.0
5    55000.0
Name: Salary, dtype: float64

In [284]:
df["Age"].fillna(method="ffill")

/tmp/ipython-input-310954073.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method="ffill")

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [285]:
df["Salary"].fillna(method="bfill")

/tmp/ipython-input-1407899343.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Salary"].fillna(method="bfill")

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4    55000.0
5    55000.0
Name: Salary, dtype: float64

In [286]:
df["Name"]= df["Name"].replace("Sai","Rose")

In [287]:
df

       Name   Age     Dept   Salary  Promoted Salary
0     Alice  25.0       HR  55000.0         550000.0
1       Bob  30.0       IT  65000.0         650000.0
2   supriya  35.0  Finance  75000.0         750000.0
3      Rose   NaN       IT  67000.0         670000.0
4  Shravani  29.0       HR      NaN              NaN
5     Alice  25.0       Hr  55000.0         550000.0

In [288]:
df_dup = df[df.duplicated(keep = "first")]
df_dup

Empty DataFrame
Columns: [Name, Age, Dept, Salary, Promoted Salary]
Index: []

In [289]:
df= df.drop_duplicates()

In [290]:
df

       Name   Age     Dept   Salary  Promoted Salary
0     Alice  25.0       HR  55000.0         550000.0
1       Bob  30.0       IT  65000.0         650000.0
2   supriya  35.0  Finance  75000.0         750000.0
3      Rose   NaN       IT  67000.0         670000.0
4  Shravani  29.0       HR      NaN              NaN
5     Alice  25.0       Hr  55000.0         550000.0

In [291]:
#invalud values
df["Promoted Salary"] = df["Promoted Salary"].apply(lambda x:x/10 if x>65000 else x)

In [292]:
df

       Name   Age     Dept   Salary  Promoted Salary
0     Alice  25.0       HR  55000.0          55000.0
1       Bob  30.0       IT  65000.0          65000.0
2   supriya  35.0  Finance  75000.0          75000.0
3      Rose   NaN       IT  67000.0          67000.0
4  Shravani  29.0       HR      NaN              NaN
5     Alice  25.0       Hr  55000.0          55000.0

In [293]:
#apply and lambda
def multiplying_age(x):
  return x*2

df["Age"] = df["Age"].apply(multiplying_age)

In [294]:
df

       Name   Age     Dept   Salary  Promoted Salary
0     Alice  50.0       HR  55000.0          55000.0
1       Bob  60.0       IT  65000.0          65000.0
2   supriya  70.0  Finance  75000.0          75000.0
3      Rose   NaN       IT  67000.0          67000.0
4  Shravani  58.0       HR      NaN              NaN
5     Alice  50.0       Hr  55000.0          55000.0

In [295]:
df["Age"].apply(lambda x:x/2)

0    25.0
1    30.0
2    35.0
3     NaN
4    29.0
5    25.0
Name: Age, dtype: float64

In [296]:
#joins and merges
department_info ={
    "Department":["HR","IT","Finance"],
    "Location":["New York","San fransice","chicago"],
    "Manager":["Laura","Steve","nina"]
}
df2=pd.DataFrame(department_info)

In [297]:
df2

  Department      Location Manager
0         HR      New York   Laura
1         IT  San fransice   Steve
2    Finance       chicago    nina

In [298]:
pd.concat([df,df2])

,Name,Age,Dept,Salary,Promoted Salary,Department,Location,Manager
0,Alice,50.0,HR,55000.0,55000.0,NaN,NaN,NaN
1,Bob,60.0,IT,65000.0,65000.0,NaN,NaN,NaN
2,supriya,70.0,Finance,75000.0,75000.0,NaN,NaN,NaN
3,Rose,NaN,IT,67000.0,67000.0,NaN,NaN,NaN
4,Shravani,58.0,HR,NaN,NaN,NaN,NaN,NaN
5,Alice,50.0,Hr,55000.0,55000.0,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,HR,New York,Laura
1,NaN,NaN,NaN,NaN,NaN,IT,San fransice,Steve
2,NaN,NaN,NaN,NaN,NaN,Finance,chicago,nina

In [299]:
pd.concat([df,df2], axis=1)

,Name,Age,Dept,Salary,Promoted Salary,Department,Location,Manager
0,Alice,50.0,HR,55000.0,55000.0,HR,New York,Laura
1,Bob,60.0,IT,65000.0,65000.0,IT,San fransice,Steve
2,supriya,70.0,Finance,75000.0,75000.0,Finance,chicago,nina
3,Rose,NaN,IT,67000.0,67000.0,NaN,NaN,NaN
4,Shravani,58.0,HR,NaN,NaN,NaN,NaN,NaN
5,Alice,50.0,Hr,55000.0,55000.0,NaN,NaN,NaN

In [300]:
df2.rename(columns={"Department":"Dept"}, inplace=True)

In [301]:
pd.merge(df,df2, on="Dept")

       Name   Age     Dept   Salary  Promoted Salary      Location Manager
0     Alice  50.0       HR  55000.0          55000.0      New York   Laura
1       Bob  60.0       IT  65000.0          65000.0  San fransice   Steve
2   supriya  70.0  Finance  75000.0          75000.0       chicago    nina
3      Rose   NaN       IT  67000.0          67000.0  San fransice   Steve
4  Shravani  58.0       HR      NaN              NaN      New York   Laura